STUW-58-IdentityServer4
PSIT4-Stuwork/stuwork pull request #11
Opened 2021-03-26 19:43 UTC by larsmos2011

tbd

2021-03-26 21:57 UTC, Zukel requested changes
Die .idea Sachen sollten nicht mit commited werden oder sie werden Probleme bei anderen mit Rider machen. Bin nicht sicher ob noch was im gitignore fehlt

2021-03-27 05:56 UTC, Marlaqk commented
> Die .idea Sachen sollten nicht mit commited werden oder sie werden Probleme bei anderen mit Rider machen. Bin nicht sicher ob noch was im gitignore fehlt

<img width="943" alt="image" src="https://user-images.githubusercontent.com/14162421/112711528-617bb500-8ec9-11eb-937c-4786e8d8e257.png">

Ich glaube du hast diesen Folder commited 😃

2021-03-27 05:57 UTC, Marlaqk commented
> Die .idea Sachen sollten nicht mit commited werden oder sie werden Probleme bei anderen mit Rider machen. Bin nicht sicher ob noch was im gitignore fehlt

<img width="622" alt="image" src="https://user-images.githubusercontent.com/14162421/112711573-aef82200-8ec9-11eb-8b98-ce9bb83e34f4.png">

Ich glaube du hast diesen Folder commited 😄

2021-03-27 09:49 UTC, Zukel approved these changes

2021-03-27 10:53 UTC, Marlaqk commented
![image](https://user-images.githubusercontent.com/14162421/112718405-0363c780-8ef3-11eb-9172-38753455cbf8.png)

This action should probably removed before merging.

2021-03-27 12:27 UTC, merged