Notizen erstellen, bearbeiten und löschen
PSIT4-Stuwork/stuwork pull request #21
Opened 2021-04-12 07:32 UTC by SilvanEgger

Closes <https://stuwork.atlassian.net/browse/STUW-63>

Implementiert erstellen, bearbeiten und löschen von Notizen.

2021-04-12 08:35 UTC, Marlaqk requested changes
I think we created a bit of a mess with the state management in this story. Probably it would be a good idea, if we invest time next sprint to setup ngrx and redux to improve our state management.

2021-04-12 08:35 UTC, Marlaqk commented on frontend/src/app/notes/file-browser/file-browser.component.css
> +  margin: 5px 5px 5px 5px;
change to `margin: 5px`

2021-04-12 08:35 UTC, Marlaqk commented on frontend/src/app/notes/file-browser/file-browser.component.html
> +      </div>
Probably this should be it's own component

2021-04-12 08:35 UTC, Marlaqk commented on frontend/src/app/notes/file-browser/file-browser.component.html
> +  <ng-template matMenuContent let-note="note">
Why is lazy rendering needed here?

2021-04-12 08:35 UTC, Marlaqk commented on frontend/src/app/notes/file-browser/file-browser.component.spec.ts
>      fixture = TestBed.createComponent(FileBrowserComponent);
add tests

2021-04-12 08:35 UTC, Marlaqk commented on frontend/src/app/notes/file-browser/file-browser.component.ts
> +  }
This seems like a hacky way... Misuse of a button in template?

2021-04-12 08:35 UTC, Marlaqk commented on frontend/src/app/notes/note/note.component.html
> +    <div *ngIf="notesService.selectedNote">
could be done like this

```
<p *ngIf="condition; else elseBlock">Content to render when condition is true.</p>
<ng-template #elseBlock>Content to render when condition is false.</ng-template>
```

2021-04-12 08:35 UTC, Marlaqk commented on frontend/src/app/notes/note/note.component.html
> +        <button mat-mini-fab color="primary" aria-label="Save note button" (click)="notesService.updateSelectedNote()">
create a local method in `compontent.ts` for `updateNote()`. Don't call service directly from template.

2021-04-12 08:35 UTC, Marlaqk commented on frontend/src/app/notes/note/note.component.html
> +                <input matInput placeholder="Placeholder" [(ngModel)]="notesService.selectedNote.title">
either add meaningful placeholder or remove it

2021-04-12 08:35 UTC, Marlaqk commented on frontend/src/app/notes/note/note.component.html
> +                <textarea matInput placeholder="Placeholder" cdkTextareaAutosize [(ngModel)]="notesService.selectedNote.content"></textarea>
either add meaningful placeholder or remove it

2021-04-12 08:35 UTC, Marlaqk commented on frontend/src/app/notes/note/note.component.spec.ts
>      fixture.detectChanges();
test for save button

2021-04-12 08:35 UTC, Marlaqk commented on frontend/src/app/notes/note/note.component.ts
> +  constructor(public notesService: NotesService) {}
In my opinion there is no reason here to expose `notesService` public. I would make it private and not access it directly from the template.

2021-04-12 08:35 UTC, Marlaqk commented on frontend/src/app/notes/file-browser/file-browser.component.html
> +      [selected]="note === notesService.selectedNote"
I don't think the service should have anything to do with the logic which note is selected in the UI...

2021-04-12 13:45 UTC, SilvanEgger commented on frontend/src/app/notes/file-browser/file-browser.component.css
> +  margin: 5px 5px 5px 5px;
done

2021-04-12 13:51 UTC, SilvanEgger commented on frontend/src/app/notes/file-browser/file-browser.component.html
> +      </div>
@Marlaqk  What exactly would you put in the component?

I suggest we create an "element-browser" component which includes the button to create a new element and the list to select an element. Then it would be a reusable component.

2021-04-12 13:57 UTC, SilvanEgger commented on frontend/src/app/notes/file-browser/file-browser.component.html
> +  <ng-template matMenuContent let-note="note">
Changed it in 494623b

2021-04-12 13:59 UTC, Marlaqk commented on frontend/src/app/notes/file-browser/file-browser.component.html
> +      </div>
I would put everything in the div into a component. Not to be reusable but to encapsulate the this part from the file-browser.html

2021-04-12 13:59 UTC, SilvanEgger commented on frontend/src/app/notes/file-browser/file-browser.component.ts
> +  }
When clicking the menu of a note it should not select the note, but only open the menu.

I had to stop the propagation of clicks to prevent it from selecting the note when clicking the menu of the note.

I had to stop the propagation of mousedowns to prevent it from showing a ripple effect on the whole note when clicking the menu of the note.

2021-04-12 14:05 UTC, Marlaqk commented on frontend/src/app/notes/file-browser/file-browser.component.ts
> +  }
Yeah but that's because the menu is inside the button. That's against the W3C HTML specification...

2021-04-12 18:10 UTC, SilvanEgger commented on frontend/src/app/notes/file-browser/file-browser.component.html
> +      </div>
this is now in a file-browser-item component

2021-04-12 18:11 UTC, SilvanEgger commented on frontend/src/app/notes/file-browser/file-browser.component.ts
> +  }
they are removed now

2021-04-12 18:15 UTC, SilvanEgger commented on frontend/src/app/notes/note/note.component.html
> +    <div *ngIf="notesService.selectedNote">
changed

2021-04-12 18:17 UTC, SilvanEgger commented on frontend/src/app/notes/note/note.component.html
> +                <input matInput placeholder="Placeholder" [(ngModel)]="notesService.selectedNote.title">
removed

2021-04-12 18:17 UTC, SilvanEgger commented on frontend/src/app/notes/note/note.component.html
> +                <textarea matInput placeholder="Placeholder" cdkTextareaAutosize [(ngModel)]="notesService.selectedNote.content"></textarea>
removed

2021-04-12 18:36 UTC, SilvanEgger commented on frontend/src/app/notes/note/note.component.ts
> +  constructor(public notesService: NotesService) {}
-> done with store implementation <https://stuwork.atlassian.net/browse/STUW-138>

2021-04-12 18:39 UTC, SilvanEgger commented on frontend/src/app/notes/file-browser/file-browser.component.html
> +      [selected]="note === notesService.selectedNote"
-> done with store implementation <https://stuwork.atlassian.net/browse/STUW-138>

2021-04-12 18:43 UTC, SilvanEgger commented on frontend/src/app/notes/note/note.component.html
> +        <button mat-mini-fab color="primary" aria-label="Save note button" (click)="notesService.updateSelectedNote()">
done

2021-04-12 18:56 UTC, Toubi01 reviewed
# Backend
In `NoteControllerTest.cs`:
- Funktion `TestNoteControllerGetById` hat überflüssige variable `notes`.
- Funktion `TestNoteControllerPut` ich würde nicht mit Id 0 testen, da es die nie geben wird in der DB (started bei Id 1).

In `NoteController.cs`:
- `[Authorize]` Kommentar müsste einkommentiert werden

# Frontend
In `notes.service.ts `:
- es wurde jeweils wieder mit der id: 0 getestet. Diese gibt es jedoch in der DB nicht, würde da auch bei der 1 beginnen. Vor allem bei `createNote()`. Bei den anderen ist es ja glaube ich einfach das erste Element im Array.


Bemerkung:
habe mich mehr auf das Backend fokussiert, da Ralph glaube ich bereits im Fronten Kommentare gemacht hat.

2021-04-13 11:18 UTC, SilvanEgger commented on frontend/src/app/notes/file-browser/file-browser.component.spec.ts
>      fixture = TestBed.createComponent(FileBrowserComponent);
created a test

2021-04-13 11:18 UTC, SilvanEgger commented on frontend/src/app/notes/note/note.component.spec.ts
>      fixture.detectChanges();
test created

2021-04-13 11:31 UTC, Marlaqk approved these changes
FE looks acceptable

2021-04-14 12:56 UTC, Toubi01 approved these changes
backend sieht auch gut aus

2021-04-15 17:26 UTC, merged