STUW 125 - Save Notes per User
PSIT4-Stuwork/stuwork pull request #28
Opened 2021-04-22 15:47 UTC by larsmos2011

Notizen sind neu mit ihrem Owner assoziert. 

- AuthContext und WebApiContext wurden gemerged. Es ist anscheinend nicht möglich, aus dem WebApiContext den User zu Verlinken, weil der User in einem IdentityDbContext ist und die Note nicht -> Laut Community sollte man am besten immer nur mit 1 Context arbeiten
- Die API erwartet nun, dass DTOs verwendet werden. Laut der .NET Community ist es eine Sünde, direkt Entities via API auszugeben.

2021-04-22 15:48 UTC, larsmos2011 commented
PR ist zurzeit `Draft`, da die Unit-Tests noch Fehlen. Das Review kann aber schon beginnen.

2021-04-23 16:58 UTC, Toubi01 requested changes
bis auf den einen `//todo handle auth` Kommentar sieht es für mich in Ordnung aus.

2021-04-23 16:58 UTC, Toubi01 commented on backend/Stuwork.Web/Controllers/RepositoryController/BaseOwnedResourceRepositoryController.cs
> +        //todo handle auth
@larsmos2011 wurde dieses todo vergessen? oder ist der Kommentar überflüssig?

2021-04-23 17:06 UTC, larsmos2011 commented on backend/Stuwork.Web/Controllers/RepositoryController/BaseOwnedResourceRepositoryController.cs
> +        //todo handle auth
Dieser Kommentar ist noch vom Boilerplate ganz am Anfang. Dort wusste ich noch nicht genau, wie wir Auth handeln werden. Der Kommentar ist überflüssig; Vielleicht sollten wir mal einen Cleanup-Task machen und gerade auch den "WeatherForecast" hinauskicken.

2021-04-23 17:43 UTC, Toubi01 approved these changes

2021-04-24 08:00 UTC, merged