STUW-62 Klassen erstellen
PSIT4-Stuwork/stuwork pull request #33
Opened 2021-05-02 16:10 UTC by Toubi01

Funktionalität der Story [STUW-62](https://stuwork.atlassian.net/browse/STUW-62) vorhanden.

Tests müssen noch angepasst / erstellt werden.

2021-05-03 13:44 UTC, Marlaqk commented
Code looks alright. For me it the screen looks strange and feels a bit awkward. I don't see why uses the same layout as the notes the screen. But I guess we had no better mockup or screen design before you started with the story.

2021-05-06 18:25 UTC, larsmos2011 approved these changes
Backend Looks good to me

2021-05-07 05:27 UTC, Marlaqk requested changes

2021-05-07 05:27 UTC, Marlaqk commented on frontend/src/app/classes/classes.component.css
> +  height: calc(100% - 128px); /* 100% - 2 * toolbar (64px header & 64px footer) */
maybe define a css variable for the toolbar space to make the calculation more descriptive

2021-05-07 05:27 UTC, Marlaqk commented on frontend/src/app/classes/classes.component.spec.ts
> +// });
remove comment

2021-05-07 05:27 UTC, Marlaqk commented on frontend/src/app/classes/classes.component.ts
> +
remove empty line

2021-05-07 05:27 UTC, Marlaqk commented on frontend/src/app/classes/classes.component.ts
> +  classClicked(id: number) {
This method is tested poorly. Two `else` paths are not taken.

2021-05-07 05:27 UTC, Marlaqk commented on frontend/src/app/classes/classes.service.ts
> +    const ourClass = {
`ourClass` is an interesting name choice

2021-05-07 05:27 UTC, Marlaqk commented on frontend/src/app/classes/classes.service.ts
> +  updateClass(ourClass: SchoolClass): Observable<SchoolClass> {
`ourClass` is an interesting name choice

2021-05-07 05:27 UTC, Marlaqk commented on frontend/src/app/notes/notes.component.ts
> +  noteClicked(id: number) {
This method is tested poorly. Two `else` paths are not taken.

2021-05-07 05:27 UTC, Marlaqk commented on frontend/src/app/shared/item-browser/item-browser-element/item-browser-element.component.spec.ts
> +  // });
remove commented test

2021-05-07 05:27 UTC, Marlaqk commented on frontend/src/app/shared/item-browser/item-browser-element/item-browser-element.component.spec.ts
> +  // });
remove commented test

2021-05-07 05:27 UTC, Marlaqk commented on frontend/src/app/shared/item-browser/item-browser-element/item-browser-element.component.spec.ts
> +  // });
remove commented test

2021-05-07 05:27 UTC, Marlaqk commented on frontend/src/app/shared/item-browser/item-browser-element/item-browser-element.component.ts
> +  @ViewChild(MatRipple) ripple: MatRipple;
`@ViewChild` is not used in code. Probably safe to remove it.

2021-05-07 05:27 UTC, Marlaqk commented on frontend/src/app/shared/item-browser/item-browser.component.spec.ts
> +  // });
remove comment

2021-05-07 07:49 UTC, Marlaqk approved these changes
lgtm

2021-05-07 10:39 UTC, merged