Stuw 193 Fusszeile soll keine Inhalte verdecken
PSIT4-Stuwork/stuwork pull request #39
Opened 2021-05-13 15:49 UTC by SilvanEgger

Kopf- und Fusszeile sollen immer angezeigt werden und sie sollen keine Inhalte verdecken.

2021-05-14 07:08 UTC, Toubi01 requested changes

2021-05-14 07:08 UTC, Toubi01 commented on frontend/src/app/app.component.css
> +  height: calc(100% - 128px); /* 100% - 2 * toolbar (64px header & 64px footer) */
Ich würde hier schönheitshalber wieder eine Variable draus machen mit einem entsprechenden Namen, damit man auch im der debug Konsole einfacher sieht um was für eine Berechnung es sich handelt.

2021-05-14 22:20 UTC, SilvanEgger commented on frontend/src/app/app.component.css
> +  height: calc(100% - 128px); /* 100% - 2 * toolbar (64px header & 64px footer) */
Find ich auch besser. Habs angepasst.

2021-05-15 04:15 UTC, Toubi01 approved these changes
sieht alles gut aus.

2021-05-15 07:26 UTC, merged