Stuw 78
PSIT4-Stuwork/stuwork pull request #8
Opened 2021-03-18 19:50 UTC by Toubi01

STUW-78 - Interface Skeleton einrichten

**Akzeptanzkriterien**:
- Angular Material ist eingebunden
- Eine Navigationsleiste ist vorhanden für Logo, User, Einstellungen usw.
- Eine Navigationsleiste ist vorhanden für Notizen, Klassen und weitere Funktionen

2021-03-18 21:37 UTC, Marlaqk requested changes
linting: 🙅 
unit test: 🙅 
cypress test: 🙅

2021-03-18 21:37 UTC, Marlaqk commented on frontend/src/app/app.component.spec.ts
> +  beforeEach(waitForAsync(() => {
Why was this change necessary?

2021-03-18 21:37 UTC, Marlaqk commented on frontend/src/app/app.component.ts
> +  isFileBrwoserOpened = true;
typo

2021-03-18 21:37 UTC, Marlaqk commented on frontend/src/app/app.component.html
> +  <mat-sidenav-content [ngStyle]="{'margin-left.px': contentMargin}">
use `ngClass` so that keeping a variable with px value is not needed in component. Create classes in your css for both cases.

https://angular.io/api/common/NgClass

2021-03-19 05:40 UTC, Toubi01 commented on frontend/src/app/app.component.spec.ts
> +  beforeEach(waitForAsync(() => {
It was done automatically when upgrading the angular cli from 9 to 11.

2021-03-19 05:42 UTC, Toubi01 commented on frontend/src/app/app.component.ts
> +  isFileBrwoserOpened = true;
what do you mean by this?

2021-03-19 06:18 UTC, Marlaqk commented on frontend/src/app/app.component.ts
> +  isFileBrwoserOpened = true;
you have a typo in `isFileBrwoserOpened`

2021-03-19 06:37 UTC, Toubi01 commented on frontend/src/app/app.component.ts
> +  isFileBrwoserOpened = true;
ah yes I see. Thx

2021-03-20 11:59 UTC, Marlaqk approved these changes

2021-03-20 12:50 UTC, merged